version: "3"
services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - sample.env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
