version: "3"
services:
  workspace:
    build:
      context: .
    image: hook_web_dev
    env_file:
      - .env
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
