# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.8
        poetry config virtualenvs.create false
        poetry install

    - name: Run pytest
      env:
        POSTGRES_DATABASE: figure_testing
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_URL: 127.0.0.1:5432
        PLURK_APP_KEY: app_key
        PLURK_APP_SECRET: app_secret
        PLURK_USER_TOKEN: user_token
        PLURK_USER_SECRET: user_secret
        SCRAPYD_URL: 127.0.0.1:6666
        FIGURE_HOOK_SECRET: IKFQX3cOo1MGs8xw-cbrwWiWxLyokSV_1SHQIYioHS4=  # A URL-safe base64-encoded 32-byte key.
        REDIS_URL: 127.0.0.1:6379
      run: |
        docker-compose -f docker-compose.test.yml --env-file sample.env up -d
        pytest